version: '0.1'
services:
  app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - '3000:3000'
      env_file: .env
      depends_on:
        - postgres
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
