image:
  repository: rapidement/poc-ephemeral-env
  pullPolicy: IfNotPresent
  # Dynamically set the tag
  tag: b2e3bf7

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
  # Dynamically set the host
  - host: test.hponthieu.com
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []

# Default important values. Do not touch it
service:
  type: ClusterIP
  port: 3000
replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

postgresql:
  enabled: true
  global:
    postgresql:
      servicePort: "5432"
  auth:
    enablePostgresUser: true
    postgresPassword: "postgres"
    username: "postgres"
    password: "postgres"
    database: "postgres"
